#!/usr/bin/env python3
"""Generate every platform icon from one source image.

Usage:  python3 tools/make_icons.py [branding/icon.png]
Needs:  Pillow  (pip install pillow, or: sudo pacman -S python-pillow)

The source must be a square PNG, ideally 1024x1024 or larger.
Outputs (commit them):
  platform/windows/nimblewood.ico             Windows exe icon
  platform/macos/nimblewood.icns              macOS app icon
  platform/ios/Assets.xcassets/AppIcon...     iOS app icon (1024, opaque)
  platform/web/favicon.png                    browser tab icon
  android/app/src/main/res/mipmap-*/          Android launcher icons
  src/icon.h                                  64x64 window icon embedded in the game
"""
import json
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
IOS_BACKGROUND = (28, 44, 36)  # iOS icons cannot be transparent; transparent areas get this color


def resized(img, size):
    return img.resize((size, size), Image.LANCZOS)


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "branding" / "icon.png"
    img = Image.open(src).convert("RGBA")
    if img.width != img.height:
        sys.exit(f"{src} must be square (it is {img.width}x{img.height}).")
    if img.width < 512:
        print(f"warning: {src} is only {img.width}px; 1024px or larger is recommended.")

    def out(rel):
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        return path

    # Windows .ico (Pillow only embeds sizes not larger than the source)
    img.save(out("platform/windows/nimblewood.ico"), format="ICO",
             sizes=[(s, s) for s in (16, 24, 32, 48, 64, 128, 256)])

    # macOS .icns
    resized(img, 1024).save(out("platform/macos/nimblewood.icns"), format="ICNS")

    # iOS: single 1024x1024 icon without alpha
    flat = Image.new("RGBA", (1024, 1024), IOS_BACKGROUND + (255,))
    flat.alpha_composite(resized(img, 1024))
    flat.convert("RGB").save(out("platform/ios/Assets.xcassets/AppIcon.appiconset/icon-1024.png"))
    (ROOT / "platform/ios/Assets.xcassets/Contents.json").write_text(
        json.dumps({"info": {"author": "xcode", "version": 1}}, indent=2) + "\n")
    (ROOT / "platform/ios/Assets.xcassets/AppIcon.appiconset/Contents.json").write_text(
        json.dumps({
            "images": [{"filename": "icon-1024.png", "idiom": "universal",
                        "platform": "ios", "size": "1024x1024"}],
            "info": {"author": "xcode", "version": 1},
        }, indent=2) + "\n")

    # Web favicon
    resized(img, 64).save(out("platform/web/favicon.png"))

    # Android launcher icons
    for density, size in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)):
        resized(img, size).save(out(f"android/app/src/main/res/mipmap-{density}/ic_launcher.png"))

    # Embedded window icon (Linux/Windows window and taskbar), raw RGBA so no image decoder is needed
    n = 64
    data = resized(img, n).tobytes()
    lines = []
    for i in range(0, len(data), 16):
        lines.append("    " + ",".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    out("src/icon.h").write_text(
        "// Generated by tools/make_icons.py - do not edit.\n"
        "#pragma once\n\n"
        f"constexpr int kIconSize = {n};\n"
        f"constexpr unsigned char kIconRGBA[{n * n * 4}] = {{\n" + "\n".join(lines) + "\n};\n")

    print("Icons generated from", src)


if __name__ == "__main__":
    main()
